name: open_meteo_api
description: a library for the open meteo api
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1
