name: weather_repository
description: a dart package which manages the weather domain
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.7

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  open_meteo_api: 
    path: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
